services:
  web:
    image: nginx:alpine
    container_name: nginx-web
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - webnet

  node:
    image: node:20-alpine
    container_name: node-sass
    working_dir: /app
    volumes:
      - ./html:/app/html
      - ./package.json:/app/package.json    # Asegúrate de montar el package.json
    command: sh -c "npm install && npm run watch:sass"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

